/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hamaster_gradesign_ibe_jni_IBENative */

#ifndef _Included_hamaster_gradesign_ibe_jni_IBENative
#define _Included_hamaster_gradesign_ibe_jni_IBENative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     hamaster_gradesign_ibe_jni_IBENative
 * Method:    setup_str
 * Signature: ([B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_hamaster_gradesign_ibe_jni_IBENative_setup_1str(JNIEnv* env, jobject obj,
						jbyteArray alpha_out,// 系统主密钥，长度20字节
						jbyteArray g_out,// 参数g，长度128字节
						jbyteArray g1_out,// 参数g1，长度128字节
						jbyteArray h_out,// 参数h，长度128字节
						jbyteArray pairing_str_in);

/*
 * Class:     hamaster_gradesign_ibe_jni_IBENative
 * Method:    keygen_str
 * Signature: ([B[B[B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_hamaster_gradesign_ibe_jni_IBENative_keygen_1str(JNIEnv* env, jobject obj,
						jbyteArray hID_out,// 私钥hID参数，长度128字节
						jbyteArray rID_out,// 私钥rID参数，长度20字节
						jbyteArray user_in,// 用户身份，如电子邮件地址
						jbyteArray alpha_in,// 系统主密钥，长度20字节
						jbyteArray g_in,// 参数g，长度128字节
						jbyteArray h_in,// 参数h，长度128字节
						jbyteArray pairing_str_in,
						jboolean random_rID);//是否随机生成rID

/*
 * Class:     hamaster_gradesign_ibe_jni_IBENative
 * Method:    encrypt_str
 * Signature: ([B[B[B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_hamaster_gradesign_ibe_jni_IBENative_encrypt_1str(JNIEnv* env, jobject obj,
						jbyteArray cipher_buffer_out,// 输出密文，长度384字节，按照uvw顺序排列
						jbyteArray plain_in,// 明文，长度128字节
						jbyteArray g_in,// 接收方参数g，长度128字节
						jbyteArray g1_in,// 接收方参数g1，长度128字节
						jbyteArray h_in,// 接收方参数h，长度128字节
						jbyteArray alice_in,// 接收方身份
						jbyteArray pairing_str_in);

/*
 * Class:     hamaster_gradesign_ibe_jni_IBENative
 * Method:    decrypt_str
 * Signature: ([B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_hamaster_gradesign_ibe_jni_IBENative_decrypt_1str(JNIEnv* env, jobject obj,
						jbyteArray plain_buffer_out,// 输出明文，长度128字节
						jbyteArray cipher_in,// 输入密文，长度384字节，按照uvw顺序排列
						jbyteArray rID_in,// 接收方私钥rID，长度20字节
						jbyteArray hID_in,// 接收方私钥hID，长度128字节
						jbyteArray pairing_str_in);

#ifdef __cplusplus
}
#endif
#endif

